from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User
from chat.models import Conversation, Message

@receiver(post_save, sender=User)
def test_message(sender, instance, created, **kwargs):
    if created:
        print(f"sender: {sender}")
        print(f"instance: {instance}")

        test_convo = Conversation.objects.create(
            user = instance,
            topic = "This was generated by a signal"
        )

        Message.objects.create(
            conversation = test_convo,
            user = instance,
            message = "This is the initial prompt",
            messages = "this is an array of messages",
            is_hidden_from_user = True,
        )
        Message.objects.create(
            conversation = test_convo,
            user = instance,
            message = "My name is X",
            messages = "this is an array of messages",
        )

